### ISSUE TITLE
【文章归档】显示不正确

### ISSUE THREAD

**Issue by sshuair** [imbyron/hexo-theme-daisy#6]
`文章归档`显示的和`首页`是一样的，并没有显示成你博客里的样子（一条一条的列表还有时间），请问这是怎么回事啊？
![image 1](https://cloud.githubusercontent.com/assets/5787131/5887633/dd08e6c8-a417-11e4-88e6-92ba88ee2062.png)

**Comment by imbyron** [comment]
修改配置文件`_config.yml`
```
# Archives
## 2: Enable pagination
## 1: Disable pagination
## 0: Fully Disable
archive: 1
category: 2
tag: 2
```
